-- GENERATED: node scripts/generate-supabase-setup.mjs
-- Sources: supabase/migrations/*.sql, in timestamp order. Do not edit this file.
-- One-time setup for a NEW project without the Nha Minh application schema.
-- No user data is deleted. Any error rolls back the entire setup.
begin;

do $setup_guard$
begin
  if exists (
    select 1 from pg_catalog.pg_tables
    where schemaname = 'public' and tablename in (
      'profiles', 'houses', 'house_members', 'pairing_invites',
      'presence_entries', 'knocks', 'notification_preferences', 'knock_dismissals'
    )
  ) then
    raise exception 'Nha Minh schema already exists. Use versioned migrations; do not rerun new-project setup.';
  end if;
end;
$setup_guard$;

-- Source: 20261001080000_create_identity_and_house.sql
-- Phase 1: Identity & House
-- Creates profiles, houses, house_members, pairing_invites
-- with RLS policies and transactional two-member enforcement.

-- ============================================================
-- profiles
-- ============================================================
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  timezone text not null default 'Asia/Ho_Chi_Minh',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Users can read their own profile.
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

-- Users can insert their own profile (bootstrap on first sign-in).
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

-- Users can update their own profile.
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ============================================================
-- houses
-- ============================================================
create type public.house_state as enum ('active', 'archived');

create table public.houses (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Nhà Mình',
  state public.house_state not null default 'active',
  created_at timestamptz not null default now()
);

alter table public.houses enable row level security;

-- Authenticated users can create a house (they must also join it in the same tx).
create policy "houses_insert_authenticated"
  on public.houses for insert
  with check (auth.uid() is not null);

-- ============================================================
-- house_members
-- ============================================================
create type public.member_status as enum ('active', 'left');

create table public.house_members (
  house_id uuid not null references public.houses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  status public.member_status not null default 'active',
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (house_id, user_id)
);

alter table public.house_members enable row level security;

-- Partner can read profile if in the same house.
create policy "profiles_select_housemate"
  on public.profiles for select
  using (
    exists (
      select 1
      from public.house_members hm1
      join public.house_members hm2
        on hm1.house_id = hm2.house_id
      where hm1.user_id = auth.uid()
        and hm2.user_id = profiles.id
        and hm1.status = 'active'
        and hm2.status = 'active'
    )
  );

-- Only members can see their house.
create policy "houses_select_member"
  on public.houses for select
  using (
    exists (
      select 1 from public.house_members
      where house_members.house_id = houses.id
        and house_members.user_id = auth.uid()
        and house_members.status = 'active'
    )
  );

-- Members can see their own house's members.
create policy "house_members_select"
  on public.house_members for select
  using (
    exists (
      select 1 from public.house_members as my
      where my.house_id = house_members.house_id
        and my.user_id = auth.uid()
        and my.status = 'active'
    )
  );

-- Authenticated users can insert themselves as members.
create policy "house_members_insert_self"
  on public.house_members for insert
  with check (
    auth.uid() = user_id
    and status = 'active'
  );

-- Members can update their own membership (e.g., leave).
create policy "house_members_update_own"
  on public.house_members for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Transactional constraint: at most 2 active members per house.
-- This is a partial unique index + trigger approach for safety.
create or replace function public.enforce_two_member_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  active_count integer;
begin
  if NEW.status <> 'active' then
    return NEW;
  end if;

  select count(*)
  into active_count
  from public.house_members
  where house_id = NEW.house_id
    and status = 'active'
    and user_id <> NEW.user_id;

  if active_count >= 2 then
    raise exception 'House already has 2 active members'
      using errcode = 'check_violation';
  end if;

  return NEW;
end;
$$;

create trigger trg_enforce_two_member_limit
  before insert or update on public.house_members
  for each row
  execute function public.enforce_two_member_limit();

-- Also add a partial index as a secondary safety net (allows at most 2 active).
-- Note: a unique index on (house_id) where status='active' limits to 1,
-- so we use an exclusion-style approach via trigger above.

-- ============================================================
-- pairing_invites
-- ============================================================
create table public.pairing_invites (
  id uuid primary key default gen_random_uuid(),
  house_id uuid not null references public.houses(id) on delete cascade,
  token_hash text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

-- Index for looking up by token hash.
create unique index pairing_invites_token_hash_idx on public.pairing_invites(token_hash);

alter table public.pairing_invites enable row level security;

-- Creator can see their own invites.
create policy "pairing_invites_select_creator"
  on public.pairing_invites for select
  using (auth.uid() = created_by);

-- Active house members can create invites.
create policy "pairing_invites_insert"
  on public.pairing_invites for insert
  with check (
    auth.uid() = created_by
    and exists (
      select 1 from public.house_members
      where house_members.house_id = pairing_invites.house_id
        and house_members.user_id = auth.uid()
        and house_members.status = 'active'
    )
  );

-- ============================================================
-- RPC: accept_pairing_invite
-- Validates token, checks expiry, checks single-use, checks house capacity,
-- then adds the user as a member. Runs as security definer for transactional safety.
-- ============================================================
create or replace function public.accept_pairing_invite(
  p_token_hash text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_invite record;
  v_active_count integer;
  v_user_id uuid;
  v_existing_membership integer;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  -- Lock the invite row.
  select *
  into v_invite
  from public.pairing_invites
  where token_hash = p_token_hash
  for update;

  if not found then
    raise exception 'Invalid invite' using errcode = 'P0002';
  end if;

  if v_invite.used_at is not null then
    raise exception 'Invite already used' using errcode = 'P0002';
  end if;

  if v_invite.expires_at < now() then
    raise exception 'Invite expired' using errcode = 'P0002';
  end if;

  if v_invite.created_by = v_user_id then
    raise exception 'Cannot accept your own invite' using errcode = 'P0002';
  end if;

  -- Check user is not already in this house.
  select count(*)
  into v_existing_membership
  from public.house_members
  where house_id = v_invite.house_id
    and user_id = v_user_id
    and status = 'active';

  if v_existing_membership > 0 then
    raise exception 'Already a member of this house' using errcode = 'P0002';
  end if;

  -- Check house capacity (must be < 2 active members).
  select count(*)
  into v_active_count
  from public.house_members
  where house_id = v_invite.house_id
    and status = 'active'
  for update;

  if v_active_count >= 2 then
    raise exception 'House is full' using errcode = 'P0002';
  end if;

  -- Mark invite as used.
  update public.pairing_invites
  set used_at = now(),
      used_by = v_user_id
  where id = v_invite.id;

  -- Add the user as a member.
  insert into public.house_members (house_id, user_id, status)
  values (v_invite.house_id, v_user_id, 'active');

  -- Ensure the new user has a profile.
  insert into public.profiles (id)
  values (v_user_id)
  on conflict (id) do nothing;

  return v_invite.house_id;
end;
$$;

-- ============================================================
-- RPC: create_house_with_owner
-- Creates a new house and adds the caller as the first member.
-- Ensures the user doesn't already have an active house.
-- ============================================================
create or replace function public.create_house_with_owner()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_existing_house uuid;
  v_house_id uuid;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  -- Check the user is not already in an active house.
  select house_id
  into v_existing_house
  from public.house_members
  where user_id = v_user_id
    and status = 'active'
  limit 1;

  if v_existing_house is not null then
    raise exception 'Already in a house' using errcode = 'P0002';
  end if;

  -- Create house.
  insert into public.houses (state)
  values ('active')
  returning id into v_house_id;

  -- Add creator as first member.
  insert into public.house_members (house_id, user_id, role, status)
  values (v_house_id, v_user_id, 'creator', 'active');

  -- Bootstrap profile if needed.
  insert into public.profiles (id)
  values (v_user_id)
  on conflict (id) do nothing;

  return v_house_id;
end;
$$;


-- Source: 20261001090000_harden_house_authorization.sql
-- Additive repair of Phase 1 authorization. No rows are deleted.
-- Invalid existing membership data causes this migration to fail safely.
alter table public.house_members add column slot smallint;

update public.house_members as member
set slot = assigned.slot
from (
  select house_id, user_id,
    row_number() over (partition by house_id order by joined_at, user_id)::smallint as slot
  from public.house_members where status = 'active'
) as assigned
where member.house_id = assigned.house_id and member.user_id = assigned.user_id;

alter table public.house_members add constraint house_members_active_slot
  check (status <> 'active' or (slot is not null and slot in (1, 2)));
create unique index house_members_active_slot_unique
  on public.house_members (house_id, slot) where status = 'active';
create unique index house_members_one_active_house
  on public.house_members (user_id) where status = 'active';

create or replace function public.is_house_member(p_house_id uuid)
returns boolean language sql stable security definer set search_path = ''
as $$
  select auth.uid() is not null and exists (
    select 1 from public.house_members m join public.houses h on h.id = m.house_id
    where m.house_id = p_house_id and m.user_id = auth.uid()
      and m.status = 'active' and h.state = 'active'
  );
$$;

create or replace function public.shares_house_with(p_user_id uuid)
returns boolean language sql stable security definer set search_path = ''
as $$
  select auth.uid() is not null and exists (
    select 1 from public.house_members mine
    join public.house_members theirs on theirs.house_id = mine.house_id
    join public.houses h on h.id = mine.house_id
    where mine.user_id = auth.uid() and theirs.user_id = p_user_id
      and mine.status = 'active' and theirs.status = 'active' and h.state = 'active'
  );
$$;

create or replace function public.current_house_id()
returns uuid language sql stable security definer set search_path = ''
as $$
  select m.house_id from public.house_members m join public.houses h on h.id = m.house_id
  where m.user_id = auth.uid() and m.status = 'active' and h.state = 'active';
$$;

revoke all on function public.is_house_member(uuid), public.shares_house_with(uuid),
  public.current_house_id() from public, anon;
grant execute on function public.is_house_member(uuid), public.shares_house_with(uuid),
  public.current_house_id() to authenticated;

drop policy if exists profiles_select_housemate on public.profiles;
create policy profiles_select_housemate on public.profiles for select to authenticated
  using (public.shares_house_with(id));
drop policy if exists houses_select_member on public.houses;
drop policy if exists houses_insert_authenticated on public.houses;
create policy houses_select_member on public.houses for select to authenticated
  using (public.is_house_member(id));
drop policy if exists house_members_select on public.house_members;
drop policy if exists house_members_insert_self on public.house_members;
drop policy if exists house_members_update_own on public.house_members;
create policy house_members_select on public.house_members for select to authenticated
  using (public.is_house_member(house_id));
drop policy if exists pairing_invites_insert on public.pairing_invites;

revoke all on public.profiles, public.houses, public.house_members, public.pairing_invites
  from public, anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.houses, public.house_members, public.pairing_invites to authenticated;

create or replace function public.enforce_two_member_limit()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  if TG_OP = 'UPDATE' and (NEW.house_id <> OLD.house_id or NEW.user_id <> OLD.user_id) then
    raise exception 'Membership keys are immutable' using errcode = '23514';
  end if;
  if NEW.status <> 'active' then return NEW; end if;
  perform 1 from public.houses where id = NEW.house_id for update;
  if not found then raise exception 'House not found' using errcode = '23503'; end if;
  if NEW.slot is null then
    select candidate into NEW.slot from generate_series(1, 2) as candidate
    where not exists (
      select 1 from public.house_members member
      where member.house_id = NEW.house_id and member.status = 'active'
        and member.slot = candidate and member.user_id <> NEW.user_id
    ) order by candidate limit 1;
  end if;
  if NEW.slot is null then
    raise exception 'House is full' using errcode = '23514';
  end if;
  return NEW;
end;
$$;
revoke all on function public.enforce_two_member_limit() from public, anon, authenticated;

create or replace function public.create_house_with_owner()
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  -- Account-level serialization also covers simultaneous creates for this user.
  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));
  if exists (select 1 from public.house_members where user_id = v_user_id and status = 'active') then
    raise exception 'Already in a house' using errcode = 'P0002';
  end if;
  insert into public.houses (state) values ('active') returning id into v_house_id;
  insert into public.house_members (house_id, user_id, role, slot)
    values (v_house_id, v_user_id, 'creator', 1);
  insert into public.profiles (id) values (v_user_id) on conflict (id) do nothing;
  return v_house_id;
end;
$$;

create or replace function public.create_pairing_invite(p_token_hash text, p_expires_at timestamptz)
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  perform 1 from public.houses where id = v_house_id for update;
  if (select count(*) from public.house_members where house_id = v_house_id and status = 'active') <> 1 then
    raise exception 'House is full' using errcode = 'P0002';
  end if;
  if p_token_hash is null or p_token_hash !~ '^[a-f0-9]{64}$'
    or p_expires_at is null or p_expires_at <= now() or p_expires_at > now() + interval '24 hours' then
    raise exception 'Invalid invite settings' using errcode = '22023';
  end if;
  insert into public.pairing_invites (house_id, token_hash, created_by, expires_at)
    values (v_house_id, p_token_hash, v_user_id, p_expires_at) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.accept_pairing_invite(p_token_hash text)
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_invite public.pairing_invites; v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));
  select * into v_invite from public.pairing_invites where token_hash = p_token_hash for update;
  if not found then raise exception 'Invalid invite' using errcode = 'P0002'; end if;
  if v_invite.used_at is not null then raise exception 'Invite already used' using errcode = 'P0002'; end if;
  if v_invite.expires_at <= now() then raise exception 'Invite expired' using errcode = 'P0002'; end if;
  if v_invite.created_by = v_user_id then raise exception 'Cannot accept your own invite' using errcode = 'P0002'; end if;
  if exists (select 1 from public.house_members where user_id = v_user_id and status = 'active') then
    raise exception 'Already in a house' using errcode = 'P0002';
  end if;
  perform 1 from public.houses where id = v_invite.house_id and state = 'active' for update;
  if not found or not exists (
    select 1 from public.house_members where house_id = v_invite.house_id
      and user_id = v_invite.created_by and status = 'active'
  ) then raise exception 'Invalid invite' using errcode = 'P0002'; end if;
  if (select count(*) from public.house_members where house_id = v_invite.house_id and status = 'active') <> 1 then
    raise exception 'House is full' using errcode = 'P0002';
  end if;
  insert into public.house_members (house_id, user_id, status)
    values (v_invite.house_id, v_user_id, 'active')
    on conflict (house_id, user_id) do update set status = 'active', slot = null, left_at = null;
  update public.pairing_invites set used_at = now(), used_by = v_user_id where id = v_invite.id;
  insert into public.profiles (id) values (v_user_id) on conflict (id) do nothing;
  return v_invite.house_id;
end;
$$;

revoke all on function public.create_house_with_owner(),
  public.create_pairing_invite(text, timestamptz), public.accept_pairing_invite(text) from public, anon;
grant execute on function public.create_house_with_owner(),
  public.create_pairing_invite(text, timestamptz), public.accept_pairing_invite(text) to authenticated;


-- Source: 20261001100000_create_presence_and_knocks.sql
-- Phase 2: explicit status, lightweight Knock, and private notification settings.
-- Writes derive the caller and their active House; direct writes are not exposed.
create table public.presence_entries (
  id uuid primary key default gen_random_uuid(),
  house_id uuid not null references public.houses(id),
  user_id uuid not null references auth.users(id),
  mood text not null check (mood in ('calm', 'happy', 'tired', 'overwhelmed', 'missing_you')),
  energy smallint not null check (energy between 1 and 3),
  availability text not null check (availability in ('available', 'later', 'quiet')),
  note text not null default '' check (char_length(note) <= 160),
  need text not null default '' check (char_length(need) <= 100),
  expires_at timestamptz,
  cleared boolean not null default false,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (house_id, user_id),
  foreign key (house_id, user_id) references public.house_members(house_id, user_id)
);
alter table public.presence_entries enable row level security;
create policy presence_entries_select on public.presence_entries for select to authenticated
  using (public.is_house_member(house_id) and (
    user_id = auth.uid() or (not cleared and (expires_at is null or expires_at > now()))
  ));

create table public.knocks (
  id uuid primary key,
  house_id uuid not null references public.houses(id),
  sender_id uuid not null references auth.users(id),
  recipient_id uuid not null references auth.users(id),
  kind text not null check (kind in ('note', 'sticker')),
  content text not null check (char_length(content) between 1 and 160),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id),
  foreign key (house_id, sender_id) references public.house_members(house_id, user_id),
  foreign key (house_id, recipient_id) references public.house_members(house_id, user_id)
);
create index knocks_house_created on public.knocks(house_id, created_at desc);
alter table public.knocks enable row level security;
create policy knocks_select on public.knocks for select to authenticated
  using (public.is_house_member(house_id) and (sender_id = auth.uid() or recipient_id = auth.uid()));

create table public.knock_dismissals (
  knock_id uuid not null references public.knocks(id),
  user_id uuid not null references auth.users(id),
  dismissed_at timestamptz not null default now(),
  primary key (knock_id, user_id)
);
alter table public.knock_dismissals enable row level security;
create policy knock_dismissals_select on public.knock_dismissals for select to authenticated
  using (user_id = auth.uid() and exists (
    select 1 from public.knocks k where k.id = knock_id and k.recipient_id = auth.uid()
      and public.is_house_member(k.house_id)
  ));

create table public.notification_preferences (
  user_id uuid primary key references auth.users(id),
  quiet_enabled boolean not null default false,
  start_minute smallint not null default 1320 check (start_minute between 0 and 1439),
  end_minute smallint not null default 420 check (end_minute between 0 and 1439),
  timezone text not null default 'Asia/Ho_Chi_Minh' check (char_length(timezone) between 1 and 100),
  preview text not null default 'generic' check (preview in ('generic', 'detail')),
  knocks_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  check (not quiet_enabled or start_minute <> end_minute)
);
alter table public.notification_preferences enable row level security;
create policy notification_preferences_select on public.notification_preferences for select to authenticated
  using (user_id = auth.uid());

revoke all on public.presence_entries, public.knocks, public.knock_dismissals,
  public.notification_preferences from public, anon, authenticated;
grant select on public.presence_entries, public.knocks, public.knock_dismissals,
  public.notification_preferences to authenticated;

create or replace function public.set_presence(
  p_mood text, p_energy integer, p_availability text, p_note text, p_need text,
  p_expires_at timestamptz, p_expected_version integer
)
returns public.presence_entries language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_row public.presence_entries;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_expected_version is null or p_expected_version < 0 or p_mood is null
    or p_mood not in ('calm', 'happy', 'tired', 'overwhelmed', 'missing_you')
    or p_energy is null or p_energy not between 1 and 3
    or p_availability is null or p_availability not in ('available', 'later', 'quiet')
    or p_note is null or char_length(p_note) > 160 or p_note ~ '[[:cntrl:]]'
    or p_need is null or char_length(p_need) > 100 or p_need ~ '[[:cntrl:]]'
    or (p_expires_at is not null and p_expires_at <= now()) then
    raise exception 'Invalid presence' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('presence:' || v_user_id::text, 0));
  select * into v_row from public.presence_entries where house_id = v_house_id and user_id = v_user_id for update;
  if coalesce(v_row.version, 0) <> p_expected_version then
    raise exception 'Presence version conflict' using errcode = '40001';
  end if;
  insert into public.presence_entries (house_id, user_id, mood, energy, availability, note, need, expires_at)
    values (v_house_id, v_user_id, p_mood, p_energy, p_availability, p_note, p_need, p_expires_at)
    on conflict (house_id, user_id) do update set
      mood = excluded.mood, energy = excluded.energy, availability = excluded.availability,
      note = excluded.note, need = excluded.need, expires_at = excluded.expires_at,
      cleared = false, version = presence_entries.version + 1, updated_at = now()
    returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.clear_presence(p_expected_version integer)
returns public.presence_entries language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_row public.presence_entries;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_expected_version is null or p_expected_version < 0 then
    raise exception 'Invalid presence version' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('presence:' || v_user_id::text, 0));
  select * into v_row from public.presence_entries where house_id = v_house_id and user_id = v_user_id for update;
  if coalesce(v_row.version, 0) <> p_expected_version then
    raise exception 'Presence version conflict' using errcode = '40001';
  end if;
  -- Keep a version even for an initially empty status, protecting delayed drafts.
  insert into public.presence_entries (house_id, user_id, mood, energy, availability, cleared, expires_at)
    values (v_house_id, v_user_id, 'calm', 2, 'quiet', true, now())
    on conflict (house_id, user_id) do update set
      cleared = true, expires_at = now(), note = '', need = '',
      version = presence_entries.version + 1, updated_at = now()
    returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.send_knock(p_operation_id uuid, p_kind text, p_content text)
returns public.knocks language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_recipient_id uuid; v_row public.knocks;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_operation_id is null or p_kind is null or p_kind not in ('note', 'sticker')
    or p_content is null or char_length(btrim(p_content)) not between 1 and 160
    or p_content ~ '[[:cntrl:]]' then
    raise exception 'Invalid Knock' using errcode = '22023';
  end if;
  if p_kind = 'sticker' and p_content not in ('leaf', 'tea', 'star', 'hug') then
    raise exception 'Invalid sticker' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('knock:' || p_operation_id::text, 0));
  select * into v_row from public.knocks where id = p_operation_id;
  if found then
    if v_row.sender_id <> v_user_id or v_row.house_id <> v_house_id
      or v_row.kind <> p_kind or v_row.content <> btrim(p_content) then
      raise exception 'Knock operation conflict' using errcode = '23505';
    end if;
    return v_row;
  end if;
  select user_id into v_recipient_id from public.house_members
    where house_id = v_house_id and status = 'active' and user_id <> v_user_id;
  if v_recipient_id is null then raise exception 'House is not paired' using errcode = 'P0002'; end if;
  insert into public.knocks (id, house_id, sender_id, recipient_id, kind, content)
    values (p_operation_id, v_house_id, v_user_id, v_recipient_id, p_kind, btrim(p_content)) returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.dismiss_knock(p_knock_id uuid)
returns boolean language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if not exists (select 1 from public.knocks
    where id = p_knock_id and recipient_id = v_user_id and public.is_house_member(house_id)) then
    raise exception 'Knock unavailable' using errcode = '42501';
  end if;
  insert into public.knock_dismissals (knock_id, user_id) values (p_knock_id, v_user_id)
    on conflict (knock_id, user_id) do nothing;
  return true;
end;
$$;

create or replace function public.set_notification_preferences(
  p_quiet_enabled boolean, p_start_minute integer, p_end_minute integer,
  p_timezone text, p_preview text, p_knocks_enabled boolean default true
)
returns public.notification_preferences language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_row public.notification_preferences;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_quiet_enabled is null or p_start_minute is null or p_start_minute not between 0 and 1439
    or p_end_minute is null or p_end_minute not between 0 and 1439
    or (p_quiet_enabled and p_start_minute = p_end_minute) or p_knocks_enabled is null
    or p_preview is null or p_preview not in ('generic', 'detail')
    or p_timezone is null or not exists (select 1 from pg_timezone_names where name = p_timezone) then
    raise exception 'Invalid notification preferences' using errcode = '22023';
  end if;
  insert into public.notification_preferences (user_id, quiet_enabled, start_minute, end_minute, timezone, preview, knocks_enabled)
    values (v_user_id, p_quiet_enabled, p_start_minute, p_end_minute, p_timezone, p_preview, p_knocks_enabled)
    on conflict (user_id) do update set quiet_enabled = excluded.quiet_enabled,
      start_minute = excluded.start_minute, end_minute = excluded.end_minute,
      timezone = excluded.timezone, preview = excluded.preview, knocks_enabled = excluded.knocks_enabled,
      updated_at = now() returning * into v_row;
  return v_row;
end;
$$;

revoke all on function public.set_presence(text, integer, text, text, text, timestamptz, integer),
  public.clear_presence(integer), public.send_knock(uuid, text, text), public.dismiss_knock(uuid),
  public.set_notification_preferences(boolean, integer, integer, text, text, boolean) from public, anon;
grant execute on function public.set_presence(text, integer, text, text, text, timestamptz, integer),
  public.clear_presence(integer), public.send_knock(uuid, text, text), public.dismiss_knock(uuid),
  public.set_notification_preferences(boolean, integer, integer, text, text, boolean) to authenticated;


notify pgrst, 'reload schema';
commit;
