-- GENERATED: node scripts/generate-supabase-setup.mjs
-- Sources: supabase/migrations/*.sql, in timestamp order. Do not edit this file.
-- One-time setup for a NEW project without the Nha Minh application schema.
-- No user data is deleted. Any error rolls back the entire setup.
begin;

do $setup_guard$
begin
  if exists (
    select 1 from pg_catalog.pg_tables
    where schemaname = 'public' and tablename in (
      'profiles', 'houses', 'house_members', 'pairing_invites',
      'presence_entries', 'knocks', 'notification_preferences', 'knock_dismissals'
    )
  ) then
    raise exception 'Nha Minh schema already exists. Use versioned migrations; do not rerun new-project setup.';
  end if;
end;
$setup_guard$;

-- Source: 20261001080000_create_identity_and_house.sql
-- Phase 1: Identity & House
-- Creates profiles, houses, house_members, pairing_invites
-- with RLS policies and transactional two-member enforcement.

-- ============================================================
-- profiles
-- ============================================================
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  timezone text not null default 'Asia/Ho_Chi_Minh',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Users can read their own profile.
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

-- Users can insert their own profile (bootstrap on first sign-in).
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

-- Users can update their own profile.
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ============================================================
-- houses
-- ============================================================
create type public.house_state as enum ('active', 'archived');

create table public.houses (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Nhà Mình',
  state public.house_state not null default 'active',
  created_at timestamptz not null default now()
);

alter table public.houses enable row level security;

-- Authenticated users can create a house (they must also join it in the same tx).
create policy "houses_insert_authenticated"
  on public.houses for insert
  with check (auth.uid() is not null);

-- ============================================================
-- house_members
-- ============================================================
create type public.member_status as enum ('active', 'left');

create table public.house_members (
  house_id uuid not null references public.houses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  status public.member_status not null default 'active',
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (house_id, user_id)
);

alter table public.house_members enable row level security;

-- Partner can read profile if in the same house.
create policy "profiles_select_housemate"
  on public.profiles for select
  using (
    exists (
      select 1
      from public.house_members hm1
      join public.house_members hm2
        on hm1.house_id = hm2.house_id
      where hm1.user_id = auth.uid()
        and hm2.user_id = profiles.id
        and hm1.status = 'active'
        and hm2.status = 'active'
    )
  );

-- Only members can see their house.
create policy "houses_select_member"
  on public.houses for select
  using (
    exists (
      select 1 from public.house_members
      where house_members.house_id = houses.id
        and house_members.user_id = auth.uid()
        and house_members.status = 'active'
    )
  );

-- Members can see their own house's members.
create policy "house_members_select"
  on public.house_members for select
  using (
    exists (
      select 1 from public.house_members as my
      where my.house_id = house_members.house_id
        and my.user_id = auth.uid()
        and my.status = 'active'
    )
  );

-- Authenticated users can insert themselves as members.
create policy "house_members_insert_self"
  on public.house_members for insert
  with check (
    auth.uid() = user_id
    and status = 'active'
  );

-- Members can update their own membership (e.g., leave).
create policy "house_members_update_own"
  on public.house_members for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Transactional constraint: at most 2 active members per house.
-- This is a partial unique index + trigger approach for safety.
create or replace function public.enforce_two_member_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  active_count integer;
begin
  if NEW.status <> 'active' then
    return NEW;
  end if;

  select count(*)
  into active_count
  from public.house_members
  where house_id = NEW.house_id
    and status = 'active'
    and user_id <> NEW.user_id;

  if active_count >= 2 then
    raise exception 'House already has 2 active members'
      using errcode = 'check_violation';
  end if;

  return NEW;
end;
$$;

create trigger trg_enforce_two_member_limit
  before insert or update on public.house_members
  for each row
  execute function public.enforce_two_member_limit();

-- Also add a partial index as a secondary safety net (allows at most 2 active).
-- Note: a unique index on (house_id) where status='active' limits to 1,
-- so we use an exclusion-style approach via trigger above.

-- ============================================================
-- pairing_invites
-- ============================================================
create table public.pairing_invites (
  id uuid primary key default gen_random_uuid(),
  house_id uuid not null references public.houses(id) on delete cascade,
  token_hash text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

-- Index for looking up by token hash.
create unique index pairing_invites_token_hash_idx on public.pairing_invites(token_hash);

alter table public.pairing_invites enable row level security;

-- Creator can see their own invites.
create policy "pairing_invites_select_creator"
  on public.pairing_invites for select
  using (auth.uid() = created_by);

-- Active house members can create invites.
create policy "pairing_invites_insert"
  on public.pairing_invites for insert
  with check (
    auth.uid() = created_by
    and exists (
      select 1 from public.house_members
      where house_members.house_id = pairing_invites.house_id
        and house_members.user_id = auth.uid()
        and house_members.status = 'active'
    )
  );

-- ============================================================
-- RPC: accept_pairing_invite
-- Validates token, checks expiry, checks single-use, checks house capacity,
-- then adds the user as a member. Runs as security definer for transactional safety.
-- ============================================================
create or replace function public.accept_pairing_invite(
  p_token_hash text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_invite record;
  v_active_count integer;
  v_user_id uuid;
  v_existing_membership integer;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  -- Lock the invite row.
  select *
  into v_invite
  from public.pairing_invites
  where token_hash = p_token_hash
  for update;

  if not found then
    raise exception 'Invalid invite' using errcode = 'P0002';
  end if;

  if v_invite.used_at is not null then
    raise exception 'Invite already used' using errcode = 'P0002';
  end if;

  if v_invite.expires_at < now() then
    raise exception 'Invite expired' using errcode = 'P0002';
  end if;

  if v_invite.created_by = v_user_id then
    raise exception 'Cannot accept your own invite' using errcode = 'P0002';
  end if;

  -- Check user is not already in this house.
  select count(*)
  into v_existing_membership
  from public.house_members
  where house_id = v_invite.house_id
    and user_id = v_user_id
    and status = 'active';

  if v_existing_membership > 0 then
    raise exception 'Already a member of this house' using errcode = 'P0002';
  end if;

  -- Check house capacity (must be < 2 active members).
  select count(*)
  into v_active_count
  from public.house_members
  where house_id = v_invite.house_id
    and status = 'active'
  for update;

  if v_active_count >= 2 then
    raise exception 'House is full' using errcode = 'P0002';
  end if;

  -- Mark invite as used.
  update public.pairing_invites
  set used_at = now(),
      used_by = v_user_id
  where id = v_invite.id;

  -- Add the user as a member.
  insert into public.house_members (house_id, user_id, status)
  values (v_invite.house_id, v_user_id, 'active');

  -- Ensure the new user has a profile.
  insert into public.profiles (id)
  values (v_user_id)
  on conflict (id) do nothing;

  return v_invite.house_id;
end;
$$;

-- ============================================================
-- RPC: create_house_with_owner
-- Creates a new house and adds the caller as the first member.
-- Ensures the user doesn't already have an active house.
-- ============================================================
create or replace function public.create_house_with_owner()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_existing_house uuid;
  v_house_id uuid;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  -- Check the user is not already in an active house.
  select house_id
  into v_existing_house
  from public.house_members
  where user_id = v_user_id
    and status = 'active'
  limit 1;

  if v_existing_house is not null then
    raise exception 'Already in a house' using errcode = 'P0002';
  end if;

  -- Create house.
  insert into public.houses (state)
  values ('active')
  returning id into v_house_id;

  -- Add creator as first member.
  insert into public.house_members (house_id, user_id, role, status)
  values (v_house_id, v_user_id, 'creator', 'active');

  -- Bootstrap profile if needed.
  insert into public.profiles (id)
  values (v_user_id)
  on conflict (id) do nothing;

  return v_house_id;
end;
$$;


-- Source: 20261001090000_harden_house_authorization.sql
-- Additive repair of Phase 1 authorization. No rows are deleted.
-- Invalid existing membership data causes this migration to fail safely.
alter table public.house_members add column slot smallint;

update public.house_members as member
set slot = assigned.slot
from (
  select house_id, user_id,
    row_number() over (partition by house_id order by joined_at, user_id)::smallint as slot
  from public.house_members where status = 'active'
) as assigned
where member.house_id = assigned.house_id and member.user_id = assigned.user_id;

alter table public.house_members add constraint house_members_active_slot
  check (status <> 'active' or (slot is not null and slot in (1, 2)));
create unique index house_members_active_slot_unique
  on public.house_members (house_id, slot) where status = 'active';
create unique index house_members_one_active_house
  on public.house_members (user_id) where status = 'active';

create or replace function public.is_house_member(p_house_id uuid)
returns boolean language sql stable security definer set search_path = ''
as $$
  select auth.uid() is not null and exists (
    select 1 from public.house_members m join public.houses h on h.id = m.house_id
    where m.house_id = p_house_id and m.user_id = auth.uid()
      and m.status = 'active' and h.state = 'active'
  );
$$;

create or replace function public.shares_house_with(p_user_id uuid)
returns boolean language sql stable security definer set search_path = ''
as $$
  select auth.uid() is not null and exists (
    select 1 from public.house_members mine
    join public.house_members theirs on theirs.house_id = mine.house_id
    join public.houses h on h.id = mine.house_id
    where mine.user_id = auth.uid() and theirs.user_id = p_user_id
      and mine.status = 'active' and theirs.status = 'active' and h.state = 'active'
  );
$$;

create or replace function public.current_house_id()
returns uuid language sql stable security definer set search_path = ''
as $$
  select m.house_id from public.house_members m join public.houses h on h.id = m.house_id
  where m.user_id = auth.uid() and m.status = 'active' and h.state = 'active';
$$;

revoke all on function public.is_house_member(uuid), public.shares_house_with(uuid),
  public.current_house_id() from public, anon;
grant execute on function public.is_house_member(uuid), public.shares_house_with(uuid),
  public.current_house_id() to authenticated;

drop policy if exists profiles_select_housemate on public.profiles;
create policy profiles_select_housemate on public.profiles for select to authenticated
  using (public.shares_house_with(id));
drop policy if exists houses_select_member on public.houses;
drop policy if exists houses_insert_authenticated on public.houses;
create policy houses_select_member on public.houses for select to authenticated
  using (public.is_house_member(id));
drop policy if exists house_members_select on public.house_members;
drop policy if exists house_members_insert_self on public.house_members;
drop policy if exists house_members_update_own on public.house_members;
create policy house_members_select on public.house_members for select to authenticated
  using (public.is_house_member(house_id));
drop policy if exists pairing_invites_insert on public.pairing_invites;

revoke all on public.profiles, public.houses, public.house_members, public.pairing_invites
  from public, anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.houses, public.house_members, public.pairing_invites to authenticated;

create or replace function public.enforce_two_member_limit()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  if TG_OP = 'UPDATE' and (NEW.house_id <> OLD.house_id or NEW.user_id <> OLD.user_id) then
    raise exception 'Membership keys are immutable' using errcode = '23514';
  end if;
  if NEW.status <> 'active' then return NEW; end if;
  perform 1 from public.houses where id = NEW.house_id for update;
  if not found then raise exception 'House not found' using errcode = '23503'; end if;
  if NEW.slot is null then
    select candidate into NEW.slot from generate_series(1, 2) as candidate
    where not exists (
      select 1 from public.house_members member
      where member.house_id = NEW.house_id and member.status = 'active'
        and member.slot = candidate and member.user_id <> NEW.user_id
    ) order by candidate limit 1;
  end if;
  if NEW.slot is null then
    raise exception 'House is full' using errcode = '23514';
  end if;
  return NEW;
end;
$$;
revoke all on function public.enforce_two_member_limit() from public, anon, authenticated;

create or replace function public.create_house_with_owner()
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  -- Account-level serialization also covers simultaneous creates for this user.
  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));
  if exists (select 1 from public.house_members where user_id = v_user_id and status = 'active') then
    raise exception 'Already in a house' using errcode = 'P0002';
  end if;
  insert into public.houses (state) values ('active') returning id into v_house_id;
  insert into public.house_members (house_id, user_id, role, slot)
    values (v_house_id, v_user_id, 'creator', 1);
  insert into public.profiles (id) values (v_user_id) on conflict (id) do nothing;
  return v_house_id;
end;
$$;

create or replace function public.create_pairing_invite(p_token_hash text, p_expires_at timestamptz)
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  perform 1 from public.houses where id = v_house_id for update;
  if (select count(*) from public.house_members where house_id = v_house_id and status = 'active') <> 1 then
    raise exception 'House is full' using errcode = 'P0002';
  end if;
  if p_token_hash is null or p_token_hash !~ '^[a-f0-9]{64}$'
    or p_expires_at is null or p_expires_at <= now() or p_expires_at > now() + interval '24 hours' then
    raise exception 'Invalid invite settings' using errcode = '22023';
  end if;
  insert into public.pairing_invites (house_id, token_hash, created_by, expires_at)
    values (v_house_id, p_token_hash, v_user_id, p_expires_at) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.accept_pairing_invite(p_token_hash text)
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_invite public.pairing_invites; v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));
  select * into v_invite from public.pairing_invites where token_hash = p_token_hash for update;
  if not found then raise exception 'Invalid invite' using errcode = 'P0002'; end if;
  if v_invite.used_at is not null then raise exception 'Invite already used' using errcode = 'P0002'; end if;
  if v_invite.expires_at <= now() then raise exception 'Invite expired' using errcode = 'P0002'; end if;
  if v_invite.created_by = v_user_id then raise exception 'Cannot accept your own invite' using errcode = 'P0002'; end if;
  if exists (select 1 from public.house_members where user_id = v_user_id and status = 'active') then
    raise exception 'Already in a house' using errcode = 'P0002';
  end if;
  perform 1 from public.houses where id = v_invite.house_id and state = 'active' for update;
  if not found or not exists (
    select 1 from public.house_members where house_id = v_invite.house_id
      and user_id = v_invite.created_by and status = 'active'
  ) then raise exception 'Invalid invite' using errcode = 'P0002'; end if;
  if (select count(*) from public.house_members where house_id = v_invite.house_id and status = 'active') <> 1 then
    raise exception 'House is full' using errcode = 'P0002';
  end if;
  insert into public.house_members (house_id, user_id, status)
    values (v_invite.house_id, v_user_id, 'active')
    on conflict (house_id, user_id) do update set status = 'active', slot = null, left_at = null;
  update public.pairing_invites set used_at = now(), used_by = v_user_id where id = v_invite.id;
  insert into public.profiles (id) values (v_user_id) on conflict (id) do nothing;
  return v_invite.house_id;
end;
$$;

revoke all on function public.create_house_with_owner(),
  public.create_pairing_invite(text, timestamptz), public.accept_pairing_invite(text) from public, anon;
grant execute on function public.create_house_with_owner(),
  public.create_pairing_invite(text, timestamptz), public.accept_pairing_invite(text) to authenticated;


-- Source: 20261001100000_create_presence_and_knocks.sql
-- Phase 2: explicit status, lightweight Knock, and private notification settings.
-- Writes derive the caller and their active House; direct writes are not exposed.
create table public.presence_entries (
  id uuid primary key default gen_random_uuid(),
  house_id uuid not null references public.houses(id),
  user_id uuid not null references auth.users(id),
  mood text not null check (mood in ('calm', 'happy', 'tired', 'overwhelmed', 'missing_you')),
  energy smallint not null check (energy between 1 and 3),
  availability text not null check (availability in ('available', 'later', 'quiet')),
  note text not null default '' check (char_length(note) <= 160),
  need text not null default '' check (char_length(need) <= 100),
  expires_at timestamptz,
  cleared boolean not null default false,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (house_id, user_id),
  foreign key (house_id, user_id) references public.house_members(house_id, user_id)
);
alter table public.presence_entries enable row level security;
create policy presence_entries_select on public.presence_entries for select to authenticated
  using (public.is_house_member(house_id) and (
    user_id = auth.uid() or (not cleared and (expires_at is null or expires_at > now()))
  ));

create table public.knocks (
  id uuid primary key,
  house_id uuid not null references public.houses(id),
  sender_id uuid not null references auth.users(id),
  recipient_id uuid not null references auth.users(id),
  kind text not null check (kind in ('note', 'sticker')),
  content text not null check (char_length(content) between 1 and 160),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id),
  foreign key (house_id, sender_id) references public.house_members(house_id, user_id),
  foreign key (house_id, recipient_id) references public.house_members(house_id, user_id)
);
create index knocks_house_created on public.knocks(house_id, created_at desc);
alter table public.knocks enable row level security;
create policy knocks_select on public.knocks for select to authenticated
  using (public.is_house_member(house_id) and (sender_id = auth.uid() or recipient_id = auth.uid()));

create table public.knock_dismissals (
  knock_id uuid not null references public.knocks(id),
  user_id uuid not null references auth.users(id),
  dismissed_at timestamptz not null default now(),
  primary key (knock_id, user_id)
);
alter table public.knock_dismissals enable row level security;
create policy knock_dismissals_select on public.knock_dismissals for select to authenticated
  using (user_id = auth.uid() and exists (
    select 1 from public.knocks k where k.id = knock_id and k.recipient_id = auth.uid()
      and public.is_house_member(k.house_id)
  ));

create table public.notification_preferences (
  user_id uuid primary key references auth.users(id),
  quiet_enabled boolean not null default false,
  start_minute smallint not null default 1320 check (start_minute between 0 and 1439),
  end_minute smallint not null default 420 check (end_minute between 0 and 1439),
  timezone text not null default 'Asia/Ho_Chi_Minh' check (char_length(timezone) between 1 and 100),
  preview text not null default 'generic' check (preview in ('generic', 'detail')),
  knocks_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  check (not quiet_enabled or start_minute <> end_minute)
);
alter table public.notification_preferences enable row level security;
create policy notification_preferences_select on public.notification_preferences for select to authenticated
  using (user_id = auth.uid());

revoke all on public.presence_entries, public.knocks, public.knock_dismissals,
  public.notification_preferences from public, anon, authenticated;
grant select on public.presence_entries, public.knocks, public.knock_dismissals,
  public.notification_preferences to authenticated;

create or replace function public.set_presence(
  p_mood text, p_energy integer, p_availability text, p_note text, p_need text,
  p_expires_at timestamptz, p_expected_version integer
)
returns public.presence_entries language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_row public.presence_entries;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_expected_version is null or p_expected_version < 0 or p_mood is null
    or p_mood not in ('calm', 'happy', 'tired', 'overwhelmed', 'missing_you')
    or p_energy is null or p_energy not between 1 and 3
    or p_availability is null or p_availability not in ('available', 'later', 'quiet')
    or p_note is null or char_length(p_note) > 160 or p_note ~ '[[:cntrl:]]'
    or p_need is null or char_length(p_need) > 100 or p_need ~ '[[:cntrl:]]'
    or (p_expires_at is not null and p_expires_at <= now()) then
    raise exception 'Invalid presence' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('presence:' || v_user_id::text, 0));
  select * into v_row from public.presence_entries where house_id = v_house_id and user_id = v_user_id for update;
  if coalesce(v_row.version, 0) <> p_expected_version then
    raise exception 'Presence version conflict' using errcode = '40001';
  end if;
  insert into public.presence_entries (house_id, user_id, mood, energy, availability, note, need, expires_at)
    values (v_house_id, v_user_id, p_mood, p_energy, p_availability, p_note, p_need, p_expires_at)
    on conflict (house_id, user_id) do update set
      mood = excluded.mood, energy = excluded.energy, availability = excluded.availability,
      note = excluded.note, need = excluded.need, expires_at = excluded.expires_at,
      cleared = false, version = presence_entries.version + 1, updated_at = now()
    returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.clear_presence(p_expected_version integer)
returns public.presence_entries language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_row public.presence_entries;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_expected_version is null or p_expected_version < 0 then
    raise exception 'Invalid presence version' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('presence:' || v_user_id::text, 0));
  select * into v_row from public.presence_entries where house_id = v_house_id and user_id = v_user_id for update;
  if coalesce(v_row.version, 0) <> p_expected_version then
    raise exception 'Presence version conflict' using errcode = '40001';
  end if;
  -- Keep a version even for an initially empty status, protecting delayed drafts.
  insert into public.presence_entries (house_id, user_id, mood, energy, availability, cleared, expires_at)
    values (v_house_id, v_user_id, 'calm', 2, 'quiet', true, now())
    on conflict (house_id, user_id) do update set
      cleared = true, expires_at = now(), note = '', need = '',
      version = presence_entries.version + 1, updated_at = now()
    returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.send_knock(p_operation_id uuid, p_kind text, p_content text)
returns public.knocks language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_house_id uuid; v_recipient_id uuid; v_row public.knocks;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_operation_id is null or p_kind is null or p_kind not in ('note', 'sticker')
    or p_content is null or char_length(btrim(p_content)) not between 1 and 160
    or p_content ~ '[[:cntrl:]]' then
    raise exception 'Invalid Knock' using errcode = '22023';
  end if;
  if p_kind = 'sticker' and p_content not in ('leaf', 'tea', 'star', 'hug') then
    raise exception 'Invalid sticker' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('knock:' || p_operation_id::text, 0));
  select * into v_row from public.knocks where id = p_operation_id;
  if found then
    if v_row.sender_id <> v_user_id or v_row.house_id <> v_house_id
      or v_row.kind <> p_kind or v_row.content <> btrim(p_content) then
      raise exception 'Knock operation conflict' using errcode = '23505';
    end if;
    return v_row;
  end if;
  select user_id into v_recipient_id from public.house_members
    where house_id = v_house_id and status = 'active' and user_id <> v_user_id;
  if v_recipient_id is null then raise exception 'House is not paired' using errcode = 'P0002'; end if;
  insert into public.knocks (id, house_id, sender_id, recipient_id, kind, content)
    values (p_operation_id, v_house_id, v_user_id, v_recipient_id, p_kind, btrim(p_content)) returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.dismiss_knock(p_knock_id uuid)
returns boolean language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if not exists (select 1 from public.knocks
    where id = p_knock_id and recipient_id = v_user_id and public.is_house_member(house_id)) then
    raise exception 'Knock unavailable' using errcode = '42501';
  end if;
  insert into public.knock_dismissals (knock_id, user_id) values (p_knock_id, v_user_id)
    on conflict (knock_id, user_id) do nothing;
  return true;
end;
$$;

create or replace function public.set_notification_preferences(
  p_quiet_enabled boolean, p_start_minute integer, p_end_minute integer,
  p_timezone text, p_preview text, p_knocks_enabled boolean default true
)
returns public.notification_preferences language plpgsql security definer set search_path = ''
as $$
declare v_user_id uuid := auth.uid(); v_row public.notification_preferences;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_quiet_enabled is null or p_start_minute is null or p_start_minute not between 0 and 1439
    or p_end_minute is null or p_end_minute not between 0 and 1439
    or (p_quiet_enabled and p_start_minute = p_end_minute) or p_knocks_enabled is null
    or p_preview is null or p_preview not in ('generic', 'detail')
    or p_timezone is null or not exists (select 1 from pg_timezone_names where name = p_timezone) then
    raise exception 'Invalid notification preferences' using errcode = '22023';
  end if;
  insert into public.notification_preferences (user_id, quiet_enabled, start_minute, end_minute, timezone, preview, knocks_enabled)
    values (v_user_id, p_quiet_enabled, p_start_minute, p_end_minute, p_timezone, p_preview, p_knocks_enabled)
    on conflict (user_id) do update set quiet_enabled = excluded.quiet_enabled,
      start_minute = excluded.start_minute, end_minute = excluded.end_minute,
      timezone = excluded.timezone, preview = excluded.preview, knocks_enabled = excluded.knocks_enabled,
      updated_at = now() returning * into v_row;
  return v_row;
end;
$$;

revoke all on function public.set_presence(text, integer, text, text, text, timestamptz, integer),
  public.clear_presence(integer), public.send_knock(uuid, text, text), public.dismiss_knock(uuid),
  public.set_notification_preferences(boolean, integer, integer, text, text, boolean) from public, anon;
grant execute on function public.set_presence(text, integer, text, text, text, timestamptz, integer),
  public.clear_presence(integer), public.send_knock(uuid, text, text), public.dismiss_knock(uuid),
  public.set_notification_preferences(boolean, integer, integer, text, text, boolean) to authenticated;


-- Source: 20261001110000_add_mascot_to_house_members.sql
-- Phase 3A: Mascot & Identity
-- Add mascot column to house_members, ensure uniqueness per house,
-- and provide RPC for assignment.

create type public.mascot_type as enum ('rabbit', 'owl');

alter table public.house_members
add column mascot public.mascot_type;

-- Ensure that within an active house, no two members have the same mascot.
create unique index house_members_unique_mascot
  on public.house_members(house_id, mascot)
  where status = 'active' and mascot is not null;

-- ============================================================
-- RPC: assign_mascot
-- Allows a user to choose their mascot. If the house has another member,
-- they will automatically receive the opposite mascot if they don't have one.
-- ============================================================
create or replace function public.assign_mascot(
  p_mascot public.mascot_type
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_house_id uuid;
  v_current_mascot public.mascot_type;
  v_partner_id uuid;
  v_partner_mascot public.mascot_type;
  v_opposite_mascot public.mascot_type;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if p_mascot = 'rabbit' then
    v_opposite_mascot := 'owl';
  else
    v_opposite_mascot := 'rabbit';
  end if;

  -- Lock the house members for this house to prevent race conditions
  select house_id, mascot
  into v_house_id, v_current_mascot
  from public.house_members
  where user_id = v_user_id and status = 'active'
  for update;

  if not found then
    raise exception 'Not in an active house' using errcode = 'P0002';
  end if;

  if v_current_mascot is not null then
    raise exception 'Mascot already assigned' using errcode = 'P0002';
  end if;

  -- Check if partner already has this mascot
  select user_id, mascot
  into v_partner_id, v_partner_mascot
  from public.house_members
  where house_id = v_house_id and user_id != v_user_id and status = 'active'
  for update;

  if found and v_partner_mascot = p_mascot then
    raise exception 'Mascot already taken by partner' using errcode = 'P0002';
  end if;

  -- Assign mascot to current user
  update public.house_members
  set mascot = p_mascot
  where house_id = v_house_id and user_id = v_user_id;

  -- Auto-assign opposite mascot to partner if they don't have one
  if found and v_partner_mascot is null then
    update public.house_members
    set mascot = v_opposite_mascot
    where house_id = v_house_id and user_id = v_partner_id;
  end if;
end;
$$;


-- Source: 20261001111500_harden_mascot_assignment.sql
-- Additive identity repair. Existing assignments and member permissions remain.
-- Serialize on the House before locking members, matching pairing's lock order.
create or replace function public.assign_mascot(p_mascot public.mascot_type)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_house_id uuid;
  v_current_mascot public.mascot_type;
  v_partner_id uuid;
  v_partner_mascot public.mascot_type;
  v_opposite_mascot public.mascot_type;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_mascot is null then
    raise exception 'Invalid mascot' using errcode = '22023';
  end if;

  v_house_id := public.current_house_id();
  if v_house_id is null then
    raise exception 'House membership required' using errcode = '42501';
  end if;
  perform 1 from public.houses where id = v_house_id and state = 'active' for update;
  if not found then
    raise exception 'Active House required' using errcode = '42501';
  end if;

  -- Recheck after the House lock: membership can change while waiting for it.
  select mascot into v_current_mascot from public.house_members
  where house_id = v_house_id and user_id = v_user_id and status = 'active'
  for update;
  if not found then
    raise exception 'House membership required' using errcode = '42501';
  end if;
  if v_current_mascot = p_mascot then return; end if; -- Safe response-loss retry.
  if v_current_mascot is not null then
    raise exception 'Mascot already assigned' using errcode = 'P0002';
  end if;

  select user_id, mascot into v_partner_id, v_partner_mascot
  from public.house_members
  where house_id = v_house_id and user_id <> v_user_id and status = 'active'
  for update;
  if v_partner_mascot = p_mascot then
    raise exception 'Mascot already taken by partner' using errcode = 'P0002';
  end if;

  v_opposite_mascot := case when p_mascot = 'rabbit' then 'owl' else 'rabbit' end;
  update public.house_members set mascot = p_mascot
  where house_id = v_house_id and user_id = v_user_id and status = 'active';
  if v_partner_id is not null and v_partner_mascot is null then
    update public.house_members set mascot = v_opposite_mascot
    where house_id = v_house_id and user_id = v_partner_id and status = 'active';
  end if;
end;
$$;

revoke all on function public.assign_mascot(public.mascot_type) from public, anon;
grant execute on function public.assign_mascot(public.mascot_type) to authenticated;


-- Source: 20261001120000_create_board_objects.sql
-- Phase 3B: Board objects (notes and links) with version check and soft deletion.

create table public.board_objects (
  id uuid primary key,
  house_id uuid not null references public.houses(id) on delete cascade,
  created_by uuid not null references auth.users(id),
  type text not null check (type in ('note', 'link')),
  payload jsonb not null default '{}'::jsonb,
  x numeric not null default 0,
  y numeric not null default 0,
  rotation numeric not null default 0,
  z_index integer not null default 0,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  foreign key (house_id, created_by) references public.house_members(house_id, user_id)
);

create index board_objects_house_id_idx on public.board_objects(house_id, deleted_at);

alter table public.board_objects enable row level security;

-- Read policy: Both members can view any non-hard-deleted object in their house.
create policy board_objects_select on public.board_objects for select to authenticated
  using (public.is_house_member(house_id));

-- We revoke direct mutation from anon/authenticated so that modifications must go through a secure RPC.
revoke insert, update, delete on public.board_objects from public, anon, authenticated;
grant select on public.board_objects to authenticated;

-- RPC for appending board objects
create or replace function public.append_board_object(
  p_id uuid,
  p_type text,
  p_payload jsonb,
  p_x numeric,
  p_y numeric,
  p_rotation numeric,
  p_z_index integer
)
returns public.board_objects language plpgsql security definer set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_house_id uuid;
  v_row public.board_objects;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_id is null or p_type not in ('note', 'link') or p_payload is null then
    raise exception 'Invalid board object data' using errcode = '22023';
  end if;

  insert into public.board_objects (
    id, house_id, created_by, type, payload, x, y, rotation, z_index
  ) values (
    p_id, v_house_id, v_user_id, p_type, p_payload, coalesce(p_x, 0), coalesce(p_y, 0), coalesce(p_rotation, 0), coalesce(p_z_index, 0)
  ) returning * into v_row;

  return v_row;
end;
$$;

-- RPC for updating or soft-deleting board objects
create or replace function public.update_board_object(
  p_id uuid,
  p_expected_version integer,
  p_payload jsonb,
  p_x numeric,
  p_y numeric,
  p_rotation numeric,
  p_z_index integer,
  p_deleted boolean
)
returns public.board_objects language plpgsql security definer set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_house_id uuid;
  v_row public.board_objects;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  v_house_id := public.current_house_id();
  if v_house_id is null then raise exception 'House membership required' using errcode = '42501'; end if;
  if p_id is null or p_expected_version is null or p_expected_version < 1 then
    raise exception 'Invalid update parameters' using errcode = '22023';
  end if;

  -- Lock the row for update
  perform pg_advisory_xact_lock(hashtextextended('board_object:' || p_id::text, 0));
  select * into v_row from public.board_objects where house_id = v_house_id and id = p_id for update;

  if v_row.id is null then
    raise exception 'Board object not found or not in this house' using errcode = 'P0002';
  end if;

  if coalesce(v_row.version, 1) <> p_expected_version then
    raise exception 'Board object version conflict' using errcode = '40001';
  end if;

  -- "Trust model": either member can update/delete any object on the board.
  update public.board_objects set
    payload = coalesce(p_payload, v_row.payload),
    x = coalesce(p_x, v_row.x),
    y = coalesce(p_y, v_row.y),
    rotation = coalesce(p_rotation, v_row.rotation),
    z_index = coalesce(p_z_index, v_row.z_index),
    version = v_row.version + 1,
    updated_at = now(),
    deleted_at = case when coalesce(p_deleted, false) = true then now() else null end
  where id = p_id returning * into v_row;

  return v_row;
end;
$$;


-- Source: 20261002010000_board_domain.sql
-- Additive repair: preserve existing Board rows and all applied migrations.
-- Both members edit; only the creator may trash/restore. No purge API.
create table public.media_objects (
  id uuid primary key,
  house_id uuid not null references public.houses(id),
  owner_id uuid not null references auth.users(id),
  media_type text not null check (media_type in ('photo', 'audio')),
  bucket_id text not null default 'nha-minh-private' check (bucket_id = 'nha-minh-private'),
  storage_path text not null unique,
  state text not null default 'pending' check (state in ('pending', 'ready', 'error')),
  mime_type text,
  size_bytes bigint,
  duration_seconds numeric,
  created_at timestamptz not null default now(),
  unique (house_id, id),
  foreign key (house_id, owner_id) references public.house_members(house_id, user_id),
  check (storage_path = house_id::text || '/' || id::text),
  check (state <> 'ready' or (
    size_bytes is not null and size_bytes > 0 and size_bytes <= 20971520 and mime_type is not null and
    ((media_type = 'photo' and mime_type in ('image/jpeg','image/png','image/webp') and duration_seconds is null) or
     (media_type = 'audio' and mime_type in ('audio/mpeg','audio/mp4','audio/ogg','audio/webm','audio/wav') and duration_seconds is not null and duration_seconds > 0 and duration_seconds <= 60))
  ))
);
alter table public.media_objects enable row level security;
revoke all on public.media_objects from public, anon, authenticated;
grant select on public.media_objects to authenticated;
create policy media_objects_select on public.media_objects for select to authenticated
  using (public.is_house_member(house_id) and (state = 'ready' or owner_id = auth.uid()));
-- Only a trusted, byte-validating media pipeline may create/update metadata.
-- No client ready-state write or public URL registration is exposed here.

alter table public.board_objects add column media_id uuid;
alter table public.board_objects add constraint board_house_item_unique unique(house_id,id);
alter table public.board_objects add constraint board_media_house_fk
  foreign key (house_id, media_id) references public.media_objects(house_id, id);
alter table public.board_objects drop constraint board_objects_type_check;
alter table public.board_objects add constraint board_objects_type_check
  check (type in ('note','link','doodle','photo','voice'));

create function public.board_payload_valid(p_type text, p_payload jsonb, p_media_id uuid)
returns boolean language plpgsql immutable set search_path = '' as $$
declare v_stroke jsonb; v_point jsonb; v_points integer := 0;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' or octet_length(p_payload::text) > 262144 then return false; end if;
  if p_type = 'note' then
    return p_media_id is null and jsonb_typeof(p_payload->'text') = 'string'
      and char_length(p_payload->>'text') <= 10000
      and regexp_replace(p_payload->>'text', E'[\n\r\t]', '', 'g') !~ '[[:cntrl:]]'
      and not exists (select 1 from jsonb_object_keys(p_payload) k where k <> 'text');
  elsif p_type = 'link' then
    return p_media_id is null and jsonb_typeof(p_payload->'url') = 'string'
      and char_length(p_payload->>'url') between 1 and 2048
      and (p_payload->>'url') ~ '^https?://[^/?#[:space:]@]+([/?#][^[:space:]]*)?$'
      and (not p_payload ? 'title' or (jsonb_typeof(p_payload->'title') = 'string' and char_length(p_payload->>'title') <= 200 and (p_payload->>'title') !~ '[[:cntrl:]]'))
      and not exists (select 1 from jsonb_object_keys(p_payload) k where k not in ('url','title'));
  elsif p_type in ('photo','voice') then
    return p_media_id is not null
      and (not p_payload ? 'caption' or (jsonb_typeof(p_payload->'caption') = 'string' and char_length(p_payload->>'caption') <= 1000 and regexp_replace(p_payload->>'caption', E'[\n\r\t]', '', 'g') !~ '[[:cntrl:]]'))
      and not exists (select 1 from jsonb_object_keys(p_payload) k where k <> 'caption');
  elsif p_type = 'doodle' then
    if p_media_id is not null or p_payload->'schemaVersion' is distinct from '1'::jsonb
      or jsonb_typeof(p_payload->'strokes') is distinct from 'array'
      or exists (select 1 from jsonb_object_keys(p_payload) k where k not in ('schemaVersion','strokes')) then return false; end if;
    if jsonb_array_length(p_payload->'strokes') > 256 then return false; end if;
    for v_stroke in select value from jsonb_array_elements(p_payload->'strokes') loop
      if jsonb_typeof(v_stroke) is distinct from 'object' or jsonb_typeof(v_stroke->'color') is distinct from 'string'
        or (v_stroke->>'color') !~ '^#[a-fA-F0-9]{6}$' or jsonb_typeof(v_stroke->'width') is distinct from 'number'
        or jsonb_typeof(v_stroke->'points') is distinct from 'array'
        or exists (select 1 from jsonb_object_keys(v_stroke) k where k not in ('color','width','points')) then return false; end if;
      if (v_stroke->>'width')::numeric not between 0.5 and 32 then return false; end if;
      v_points := v_points + jsonb_array_length(v_stroke->'points');
      if v_points > 10000 then return false; end if;
      for v_point in select value from jsonb_array_elements(v_stroke->'points') loop
        if jsonb_typeof(v_point) <> 'array' then return false; end if;
        if jsonb_array_length(v_point) <> 2 or jsonb_typeof(v_point->0) <> 'number' or jsonb_typeof(v_point->1) <> 'number' then return false; end if;
        if (v_point->>0)::numeric not between -10000 and 10000 or (v_point->>1)::numeric not between -10000 and 10000 then return false; end if;
      end loop;
    end loop;
    return true;
  end if;
  return false;
exception when others then return false;
end;
$$;
revoke all on function public.board_payload_valid(text,jsonb,uuid) from public, anon;
grant execute on function public.board_payload_valid(text,jsonb,uuid) to authenticated;
-- NOT VALID preserves old invalid rows; all new/modified rows are checked.
alter table public.board_objects add constraint board_payload_bounds
  check (public.board_payload_valid(type,payload,media_id) is true) not valid;
alter table public.board_objects add constraint board_layout_bounds
  check (x between -10000 and 10000 and y between -10000 and 10000
    and rotation between -180 and 180 and z_index between 0 and 1000000) not valid;

create table public.board_operations (
  operation_id uuid primary key,
  house_id uuid not null references public.houses(id),
  actor_id uuid not null references auth.users(id),
  item_id uuid not null,
  request jsonb not null,
  outcome text not null check (outcome in ('applied','conflict')),
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  foreign key (house_id,actor_id) references public.house_members(house_id,user_id),
  foreign key (house_id,item_id) references public.board_objects(house_id,id)
);
alter table public.board_operations enable row level security;
revoke all on public.board_objects, public.board_operations from public, anon, authenticated;
grant select on public.board_objects, public.board_operations to authenticated;
create policy board_operations_select on public.board_operations for select to authenticated
  using (actor_id = auth.uid() and public.is_house_member(house_id));

-- Retire insecure legacy write entry points without deleting their definitions.
revoke all on function public.append_board_object(uuid,text,jsonb,numeric,numeric,numeric,integer),
  public.update_board_object(uuid,integer,jsonb,numeric,numeric,numeric,integer,boolean)
  from public, anon, authenticated;

create function public.apply_board_operation(
  p_operation_id uuid, p_house_id uuid, p_mutation text,
  p_item_id uuid, p_expected_version integer, p_data jsonb
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := auth.uid(); v_request jsonb; v_previous public.board_operations;
  v_item public.board_objects; v_outcome text := 'applied'; v_media public.media_objects; v_key text;
begin
  if v_actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_operation_id is null or p_item_id is null or p_house_id is null
    or p_mutation is null or p_mutation not in ('append','update','trash','restore')
    or p_data is null or jsonb_typeof(p_data) <> 'object' or octet_length(p_data::text) > 300000
    or p_expected_version is null then raise exception 'Invalid operation' using errcode = '22023'; end if;
  if public.current_house_id() is distinct from p_house_id then raise exception 'House membership required' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('board_operation:' || p_operation_id::text,0));
  perform 1 from public.houses where id = p_house_id and state = 'active' for update;
  if not found then raise exception 'Active House required' using errcode = '42501'; end if;
  perform 1 from public.house_members where house_id = p_house_id and user_id = v_actor and status = 'active' for share;
  if not found then raise exception 'House membership required' using errcode = '42501'; end if;
  v_request := jsonb_build_object('mutation',p_mutation,'itemId',p_item_id,'expectedVersion',p_expected_version,'data',p_data);
  select * into v_previous from public.board_operations where operation_id = p_operation_id;
  if found then
    if v_previous.house_id <> p_house_id or v_previous.actor_id <> v_actor or v_previous.request <> v_request then
      raise exception 'Operation identity mismatch' using errcode = '23505';
    end if;
    return jsonb_build_object('operation_id',p_operation_id,'house_id',p_house_id,'actor_id',v_actor,'outcome',v_previous.outcome,'item',v_previous.snapshot);
  end if;

  if p_mutation = 'append' then
    if p_expected_version <> 0 or exists (select 1 from jsonb_object_keys(p_data) k where k not in ('type','payload','mediaId','x','y','rotation','zIndex'))
      or jsonb_typeof(p_data->'type') <> 'string' or not p_data ? 'payload' then raise exception 'Invalid append' using errcode = '22023'; end if;
    v_item.id := p_item_id; v_item.house_id := p_house_id; v_item.created_by := v_actor;
    v_item.type := p_data->>'type'; v_item.payload := p_data->'payload';
    v_item.media_id := (p_data->>'mediaId')::uuid;
    v_item.x := coalesce((p_data->>'x')::numeric,0); v_item.y := coalesce((p_data->>'y')::numeric,0);
    v_item.rotation := coalesce((p_data->>'rotation')::numeric,0); v_item.z_index := coalesce((p_data->>'zIndex')::integer,0);
  else
    if p_expected_version < 1 then raise exception 'Invalid version' using errcode = '22023'; end if;
    select * into v_item from public.board_objects where id = p_item_id and house_id = p_house_id for update;
    if not found then raise exception 'Board object unavailable' using errcode = 'P0002'; end if;
    if p_mutation in ('trash','restore') and v_item.created_by <> v_actor then raise exception 'Creator required' using errcode = '42501'; end if;
    if v_item.version <> p_expected_version then v_outcome := 'conflict';
    elsif p_mutation = 'update' then
      if v_item.deleted_at is not null then raise exception 'Object is in trash' using errcode = 'P0002'; end if;
      if p_data = '{}'::jsonb or exists (select 1 from jsonb_object_keys(p_data) k where k not in ('payload','mediaId','x','y','rotation','zIndex')) then raise exception 'Invalid update' using errcode = '22023'; end if;
      if p_data ? 'payload' then v_item.payload := p_data->'payload'; end if;
      if p_data ? 'mediaId' then v_item.media_id := (p_data->>'mediaId')::uuid; end if;
      if p_data ? 'x' then v_item.x := (p_data->>'x')::numeric; end if;
      if p_data ? 'y' then v_item.y := (p_data->>'y')::numeric; end if;
      if p_data ? 'rotation' then v_item.rotation := (p_data->>'rotation')::numeric; end if;
      if p_data ? 'zIndex' then v_item.z_index := (p_data->>'zIndex')::integer; end if;
    elsif p_data <> '{}'::jsonb or (p_mutation = 'trash' and v_item.deleted_at is not null) or (p_mutation = 'restore' and v_item.deleted_at is null) then
      raise exception 'Invalid trash transition' using errcode = '22023';
    end if;
  end if;

  for v_key in select unnest(array['x','y','rotation','zIndex']) loop
    if p_data ? v_key and jsonb_typeof(p_data->v_key) is distinct from 'number' then raise exception 'Invalid layout type' using errcode = '22023'; end if;
  end loop;

  if v_outcome = 'applied' then
    if public.board_payload_valid(v_item.type,v_item.payload,v_item.media_id) is not true
      or v_item.x is null or v_item.y is null or v_item.rotation is null or v_item.z_index is null
      or v_item.x not between -10000 and 10000 or v_item.y not between -10000 and 10000
      or v_item.rotation not between -180 and 180 or v_item.z_index not between 0 and 1000000 then
      raise exception 'Invalid Board content' using errcode = '22023';
    end if;
    if v_item.media_id is not null then
      select * into v_media from public.media_objects where id = v_item.media_id and house_id = p_house_id and state = 'ready' for share;
      if not found or (v_item.type = 'photo' and v_media.media_type <> 'photo') or (v_item.type = 'voice' and v_media.media_type <> 'audio') then
        raise exception 'Media unavailable' using errcode = '42501';
      end if;
    end if;
    if p_mutation = 'append' then
      insert into public.board_objects(id,house_id,created_by,type,payload,media_id,x,y,rotation,z_index)
        values(v_item.id,p_house_id,v_actor,v_item.type,v_item.payload,v_item.media_id,v_item.x,v_item.y,v_item.rotation,v_item.z_index) returning * into v_item;
    else
      update public.board_objects set payload=v_item.payload, media_id=v_item.media_id,
        x=v_item.x, y=v_item.y, rotation=v_item.rotation, z_index=v_item.z_index,
        version=version+1, updated_at=now(),
        deleted_at=case when p_mutation='trash' then now() when p_mutation='restore' then null else deleted_at end
      where id=p_item_id and house_id=p_house_id returning * into v_item;
    end if;
  end if;
  insert into public.board_operations(operation_id,house_id,actor_id,item_id,request,outcome,snapshot)
    values(p_operation_id,p_house_id,v_actor,p_item_id,v_request,v_outcome,to_jsonb(v_item));
  return jsonb_build_object('operation_id',p_operation_id,'house_id',p_house_id,'actor_id',v_actor,'outcome',v_outcome,'item',to_jsonb(v_item));
end;
$$;
revoke all on function public.apply_board_operation(uuid,uuid,text,uuid,integer,jsonb) from public, anon;
grant execute on function public.apply_board_operation(uuid,uuid,text,uuid,integer,jsonb) to authenticated;


-- Source: 20261002020000_whiteboard_snapshots.sql
-- Additive Whiteboard snapshots; no media, public rooms, deletion or realtime.
create function public.whiteboard_number(v jsonb, lo numeric, hi numeric, whole boolean default false)
returns boolean language sql immutable set search_path = '' as $$
  select case when jsonb_typeof(v) = 'number' then (v::text)::numeric between lo and hi
    and (not whole or trunc((v::text)::numeric) = (v::text)::numeric) else false end
$$;
create function public.whiteboard_id(v jsonb) returns boolean language sql immutable set search_path = '' as $$
  select coalesce(jsonb_typeof(v) = 'string' and (v #>> '{}') ~ '^[A-Za-z0-9_-]{1,128}$',false)
$$;
create function public.whiteboard_point(v jsonb) returns boolean language plpgsql immutable set search_path = '' as $$
begin
  if jsonb_typeof(v) is distinct from 'array' then return false; end if;
  if jsonb_array_length(v) <> 2 then return false; end if;
  return public.whiteboard_number(v->0,-100000,100000) and public.whiteboard_number(v->1,-100000,100000);
end;
$$;
create function public.whiteboard_binding(v jsonb) returns boolean language plpgsql immutable set search_path = '' as $$
begin
  if v = 'null'::jsonb then return true; end if;
  if jsonb_typeof(v) is distinct from 'object' then return false; end if;
  return not exists(select 1 from jsonb_object_keys(v) as f(key_name) where f.key_name not in ('elementId','focus','gap'))
    and public.whiteboard_id(v->'elementId') and public.whiteboard_number(v->'focus',-1,1) and public.whiteboard_number(v->'gap',0,100000);
end;
$$;
create function public.whiteboard_scene_valid(s jsonb) returns boolean language plpgsql immutable set search_path = '' as $$
declare
  e jsonb; v jsonb; p jsonb; k text; ids text[] := '{}'; references_to text[] := '{}'; n integer := 0;
  common text[] := array['id','type','x','y','width','height','angle','strokeColor','backgroundColor','fillStyle','strokeWidth','strokeStyle','roughness','opacity','seed','version','versionNonce','isDeleted','groupIds','frameId','boundElements','updated','link','locked','roundness','index'];
  extra text[];
begin
  if jsonb_typeof(s) is distinct from 'object' or octet_length(s::text) > 1048576 then return false; end if;
  if exists(select 1 from jsonb_object_keys(s) as f(key_name) where f.key_name not in ('schemaVersion','library','libraryVersion','elements'))
    or s->'schemaVersion' is distinct from '1'::jsonb or s->>'library' is distinct from 'excalidraw'
    or s->>'libraryVersion' is distinct from '0.18.1' or jsonb_typeof(s->'elements') is distinct from 'array' then return false; end if;
  if jsonb_array_length(s->'elements') > 1000 then return false; end if;
  for e in select value from jsonb_array_elements(s->'elements') loop
    if jsonb_typeof(e) is distinct from 'object' then return false; end if;
    if e->>'type' is null or e->>'type' not in ('rectangle','ellipse','diamond','text','freedraw','line','arrow')
      or public.whiteboard_id(e->'id') is not true or (e->>'id') = any(ids) or not e ?& common then return false; end if;
    ids := array_append(ids,e->>'id');
    extra := case e->>'type'
      when 'text' then array['fontSize','fontFamily','text','originalText','textAlign','verticalAlign','containerId','autoResize','lineHeight']
      when 'freedraw' then array['points','pressures','simulatePressure','lastCommittedPoint']
      when 'line' then array['points','lastCommittedPoint','startBinding','endBinding','startArrowhead','endArrowhead','elbowed']
      when 'arrow' then array['points','lastCommittedPoint','startBinding','endBinding','startArrowhead','endArrowhead','elbowed'] else '{}'::text[] end;
    if exists(select 1 from jsonb_object_keys(e) as f(key_name) where not f.key_name = any(common || extra)) then return false; end if;
    for k,v in select key,value from jsonb_each(e) loop
      if (case
        when k in ('id') then public.whiteboard_id(v)
        when k in ('x','y') then public.whiteboard_number(v,-100000,100000)
        when k in ('width','height') then public.whiteboard_number(v,0,100000)
        when k = 'angle' then public.whiteboard_number(v,-100,100)
        when k in ('strokeColor','backgroundColor') then jsonb_typeof(v) = 'string' and (v #>> '{}') ~ '^(transparent|#[0-9a-fA-F]{3,8})$'
        when k = 'fillStyle' then v #>> '{}' in ('hachure','cross-hatch','solid','zigzag')
        when k = 'strokeStyle' then v #>> '{}' in ('solid','dashed','dotted')
        when k = 'strokeWidth' then public.whiteboard_number(v,0,32)
        when k = 'roughness' then public.whiteboard_number(v,0,5)
        when k = 'opacity' then public.whiteboard_number(v,0,100)
        when k in ('seed','versionNonce') then public.whiteboard_number(v,0,2147483647,true)
        when k = 'version' then public.whiteboard_number(v,1,2147483647,true)
        when k = 'updated' then public.whiteboard_number(v,0,9007199254740991,true)
        when k in ('isDeleted','locked','simulatePressure','autoResize') then jsonb_typeof(v) = 'boolean'
        when k in ('link','frameId') then v = 'null'::jsonb
        when k = 'index' then v = 'null'::jsonb or jsonb_typeof(v) = 'string' and (v #>> '{}') ~ '^[A-Za-z0-9]{1,128}$'
        when k in ('lastCommittedPoint') then v = 'null'::jsonb or public.whiteboard_point(v)
        when k in ('startBinding','endBinding') then public.whiteboard_binding(v)
        when k in ('startArrowhead','endArrowhead') then v = 'null'::jsonb or v #>> '{}' in ('arrow','bar','dot','circle','circle_outline','triangle','triangle_outline','diamond','diamond_outline','crowfoot_one','crowfoot_many','crowfoot_one_or_many')
        when k = 'elbowed' then v = 'false'::jsonb
        when k = 'fontSize' then public.whiteboard_number(v,4,512)
        when k = 'fontFamily' then public.whiteboard_number(v,1,10,true) and v #>> '{}' in ('2','5')
        when k = 'lineHeight' then public.whiteboard_number(v,.5,5)
        when k in ('text','originalText') then jsonb_typeof(v) = 'string' and length(v #>> '{}') <= 10000 and (v #>> '{}') !~ '[\x01-\x08\x0B\x0C\x0E-\x1F\x7F]'
        when k = 'textAlign' then v #>> '{}' in ('left','center','right')
        when k = 'verticalAlign' then v #>> '{}' in ('top','middle','bottom')
        when k = 'containerId' then v = 'null'::jsonb or public.whiteboard_id(v)
        else true end) is not true then return false; end if;
    end loop;
    v := e->'groupIds';
    if jsonb_typeof(v) is distinct from 'array' then return false; end if;
    if jsonb_array_length(v) > 32 or exists(select 1 from jsonb_array_elements(v) x where public.whiteboard_id(x) is not true) then return false; end if;
    v := e->'roundness';
    if v <> 'null'::jsonb then
      if jsonb_typeof(v) is distinct from 'object' then return false; end if;
      if exists(select 1 from jsonb_object_keys(v) as f(key_name) where f.key_name not in ('type','value')) or public.whiteboard_number(v->'type',1,3,true) is not true
        or (v ? 'value' and public.whiteboard_number(v->'value',0,100000) is not true) then return false; end if;
    end if;
    v := e->'boundElements';
    if v <> 'null'::jsonb then
      if jsonb_typeof(v) is distinct from 'array' then return false; end if;
      if jsonb_array_length(v) > 1000 then return false; end if;
      for p in select value from jsonb_array_elements(v) loop
        if jsonb_typeof(p) is distinct from 'object' then return false; end if;
        if exists(select 1 from jsonb_object_keys(p) as f(key_name) where f.key_name not in ('id','type')) or public.whiteboard_id(p->'id') is not true or p->>'type' is null or p->>'type' not in ('text','arrow') then return false; end if;
        references_to := array_append(references_to,p->>'id');
      end loop;
    end if;
    if e->>'type' = 'text' then
      if not e ?& extra then return false; end if;
      if e->'containerId' <> 'null'::jsonb then references_to := array_append(references_to,e->>'containerId'); end if;
    end if;
    if e->>'type' in ('freedraw','line','arrow') then
      if jsonb_typeof(e->'points') is distinct from 'array' or not e ? 'lastCommittedPoint' then return false; end if;
      n := n + jsonb_array_length(e->'points');
      if n > 20000 or exists(select 1 from jsonb_array_elements(e->'points') x where public.whiteboard_point(x) is not true) then return false; end if;
      if e->>'type' = 'freedraw' then
        if jsonb_typeof(e->'pressures') is distinct from 'array' or jsonb_typeof(e->'simulatePressure') is distinct from 'boolean' then return false; end if;
        if jsonb_array_length(e->'pressures') > jsonb_array_length(e->'points') or exists(select 1 from jsonb_array_elements(e->'pressures') x where public.whiteboard_number(x,0,1) is not true) then return false; end if;
      else
        if not e ?& array['startBinding','endBinding','startArrowhead','endArrowhead'] or (e->>'type' = 'arrow' and e->'elbowed' is distinct from 'false'::jsonb) then return false; end if;
        foreach k in array array['startBinding','endBinding'] loop
          if e->k <> 'null'::jsonb then references_to := array_append(references_to,e->k->>'elementId'); end if;
        end loop;
      end if;
    end if;
  end loop;
  return references_to <@ ids;
end;
$$;

create table public.whiteboards (
  id uuid primary key default gen_random_uuid(),
  house_id uuid not null unique references public.houses(id),
  version integer not null check(version >= 1),
  scene jsonb not null check(public.whiteboard_scene_valid(scene)),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(house_id,updated_by) references public.house_members(house_id,user_id)
);
create table public.whiteboard_operations (
  operation_id uuid primary key,
  house_id uuid not null references public.whiteboards(house_id),
  actor_id uuid not null references auth.users(id),
  request jsonb not null,
  outcome text not null check(outcome in ('applied','conflict')),
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  foreign key(house_id,actor_id) references public.house_members(house_id,user_id)
);
alter table public.whiteboards enable row level security;
alter table public.whiteboard_operations enable row level security;
revoke all on public.whiteboards,public.whiteboard_operations from public,anon,authenticated;
grant select on public.whiteboards,public.whiteboard_operations to authenticated;
create policy whiteboards_select on public.whiteboards for select to authenticated using (
  public.is_house_member(house_id) and exists(select 1 from public.houses h where h.id = house_id and h.state = 'active')
);
create policy whiteboard_operations_select on public.whiteboard_operations for select to authenticated using (
  actor_id = auth.uid() and public.is_house_member(house_id) and exists(select 1 from public.houses h where h.id = house_id and h.state = 'active')
);
create function public.save_whiteboard_snapshot(p_operation_id uuid,p_house_id uuid,p_expected_version integer,p_scene jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  actor uuid := auth.uid(); previous public.whiteboard_operations; current_board public.whiteboards;
  request jsonb; result jsonb; outcome text := 'applied';
begin
  if actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_operation_id is null or p_house_id is null or p_expected_version is null or p_expected_version not between 0 and 2147483646
    or public.whiteboard_scene_valid(p_scene) is not true then raise exception 'Invalid Whiteboard operation' using errcode = '22023'; end if;
  if public.current_house_id() is distinct from p_house_id then raise exception 'House required' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('whiteboard_operation:' || p_operation_id::text,0));
  perform 1 from public.houses where id = p_house_id and state = 'active' for update;
  if not found then raise exception 'Active House required' using errcode = '42501'; end if;
  perform 1 from public.house_members where house_id = p_house_id and user_id = actor and status = 'active' for share;
  if not found then raise exception 'Active member required' using errcode = '42501'; end if;
  request := jsonb_build_object('expectedVersion',p_expected_version,'scene',p_scene);
  select * into previous from public.whiteboard_operations where operation_id = p_operation_id;
  if found then
    if previous.house_id <> p_house_id or previous.actor_id <> actor or previous.request <> request then raise exception 'Operation identity mismatch' using errcode = '23505'; end if;
    return jsonb_build_object('operationId',p_operation_id,'actorId',actor,'houseId',p_house_id,'outcome',previous.outcome,'snapshot',previous.snapshot);
  end if;
  select * into current_board from public.whiteboards where house_id = p_house_id for update;
  if coalesce(current_board.version,0) <> p_expected_version then
    if current_board.version is null then raise exception 'Whiteboard unavailable' using errcode = 'P0002'; end if;
    outcome := 'conflict';
  else
    insert into public.whiteboards(house_id,version,scene,updated_by) values(p_house_id,1,p_scene,actor)
      on conflict(house_id) do update set version = public.whiteboards.version + 1, scene = p_scene, updated_by = actor, updated_at = now()
      returning * into current_board;
  end if;
  result := jsonb_build_object('houseId',p_house_id,'version',current_board.version,'scene',current_board.scene,'updatedBy',current_board.updated_by,'updatedAt',current_board.updated_at);
  insert into public.whiteboard_operations(operation_id,house_id,actor_id,request,outcome,snapshot) values(p_operation_id,p_house_id,actor,request,outcome,result);
  return jsonb_build_object('operationId',p_operation_id,'actorId',actor,'houseId',p_house_id,'outcome',outcome,'snapshot',result);
end;
$$;
revoke all on function public.save_whiteboard_snapshot(uuid,uuid,integer,jsonb) from public,anon;
grant execute on function public.save_whiteboard_snapshot(uuid,uuid,integer,jsonb) to authenticated;


notify pgrst, 'reload schema';
commit;
